import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BarChart3, TrendingUp, DollarSign } from 'lucide-react';
import { useTheme } from '../components/Theme/ThemeProvider';
export const BacktestView = () => {
    const { theme } = useTheme();
    return (_jsxs("div", { className: "p-6", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h1", { className: `text-3xl font-bold mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Strategy Backtesting" }), _jsx("p", { className: `${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Strategy validation and performance analysis" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-4 gap-6 mb-6", children: [_jsx("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Total Return" }), _jsx("p", { className: "text-2xl font-bold text-green-400", children: "+127.3%" })] }), _jsx(TrendingUp, { className: "w-8 h-8 text-green-400" })] }) }), _jsx("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Sharpe Ratio" }), _jsx("p", { className: "text-2xl font-bold text-blue-400", children: "1.85" })] }), _jsx(BarChart3, { className: "w-8 h-8 text-blue-400" })] }) }), _jsx("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Max Drawdown" }), _jsx("p", { className: "text-2xl font-bold text-red-400", children: "-8.7%" })] }), _jsx(TrendingUp, { className: "w-8 h-8 text-red-400 transform rotate-180" })] }) }), _jsx("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Win Rate" }), _jsx("p", { className: "text-2xl font-bold text-purple-400", children: "68.4%" })] }), _jsx(DollarSign, { className: "w-8 h-8 text-purple-400" })] }) })] }), _jsxs("div", { className: `${theme === 'dark'
                    ? 'bg-white/10 border-blue-800/30'
                    : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsx("h3", { className: `text-lg font-semibold mb-4 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Equity Curve" }), _jsx("div", { className: "h-64 flex items-center justify-center", children: _jsx("p", { className: `${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Backtesting engine will be implemented in Phase 4" }) })] })] }));
};
