import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TrendingUp, BarChart3, Activity } from 'lucide-react';
import { useTheme } from '../components/Theme/ThemeProvider';
export const ChartingView = () => {
    const { theme } = useTheme();
    return (_jsxs("div", { className: "p-6", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h1", { className: `text-3xl font-bold mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Advanced Charting" }), _jsx("p", { className: `${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "TradingView-style charts with AI overlays and pattern recognition" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsx("div", { className: "lg:col-span-2", children: _jsx("div", { className: `${theme === 'dark'
                                ? 'bg-white/10 border-blue-800/30'
                                : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border h-96`, children: _jsx("div", { className: "flex items-center justify-center h-full", children: _jsxs("div", { className: "text-center", children: [_jsx(TrendingUp, { className: `w-16 h-16 mx-auto mb-4 ${theme === 'dark' ? 'text-blue-400' : 'text-blue-500'}` }), _jsx("h3", { className: `text-xl font-semibold mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Interactive Chart" }), _jsx("p", { className: `${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Advanced charting engine will be implemented in Phase 2" })] }) }) }) }), _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: `${theme === 'dark'
                                    ? 'bg-white/10 border-blue-800/30'
                                    : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(BarChart3, { className: "w-5 h-5 mr-2 text-blue-400" }), "Chart Settings"] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsx("label", { className: `block text-sm font-medium mb-1 ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Timeframe" }), _jsxs("select", { className: `w-full px-3 py-2 rounded-lg border ${theme === 'dark'
                                                            ? 'bg-gray-800 border-gray-600 text-white'
                                                            : 'bg-white border-gray-300 text-gray-900'}`, children: [_jsx("option", { children: "1m" }), _jsx("option", { children: "5m" }), _jsx("option", { children: "15m" }), _jsx("option", { children: "1h" }), _jsx("option", { children: "4h" }), _jsx("option", { children: "1d" })] })] }), _jsxs("div", { children: [_jsx("label", { className: `block text-sm font-medium mb-1 ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Chart Type" }), _jsxs("select", { className: `w-full px-3 py-2 rounded-lg border ${theme === 'dark'
                                                            ? 'bg-gray-800 border-gray-600 text-white'
                                                            : 'bg-white border-gray-300 text-gray-900'}`, children: [_jsx("option", { children: "Candlestick" }), _jsx("option", { children: "Line" }), _jsx("option", { children: "Area" }), _jsx("option", { children: "Heikin-Ashi" })] })] })] })] }), _jsxs("div", { className: `${theme === 'dark'
                                    ? 'bg-white/10 border-blue-800/30'
                                    : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(Activity, { className: "w-5 h-5 mr-2 text-green-400" }), "Indicators"] }), _jsx("div", { className: "space-y-2", children: ['Moving Averages', 'RSI', 'MACD', 'Bollinger Bands', 'Volume'].map((indicator) => (_jsxs("label", { className: "flex items-center", children: [_jsx("input", { type: "checkbox", className: "mr-2 rounded", defaultChecked: indicator === 'Moving Averages' }), _jsx("span", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: indicator })] }, indicator))) })] })] })] })] }));
};
