import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Shield, AlertTriangle, TrendingDown } from 'lucide-react';
import { useTheme } from '../components/Theme/ThemeProvider';
export const RiskView = () => {
    const { theme } = useTheme();
    return (_jsxs("div", { className: "p-6", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h1", { className: `text-3xl font-bold mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Risk Management Center" }), _jsx("p", { className: `${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Advanced risk analytics with position sizing and portfolio optimization" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsxs("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(Shield, { className: "w-5 h-5 mr-2 text-green-400" }), "Portfolio Risk"] }), _jsxs("div", { className: "space-y-4", children: [_jsx("div", { children: _jsxs("div", { className: "flex justify-between text-sm mb-1", children: [_jsx("span", { className: `${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Value at Risk (95%)" }), _jsx("span", { className: "text-red-400", children: "-$2,450" })] }) }), _jsx("div", { children: _jsxs("div", { className: "flex justify-between text-sm mb-1", children: [_jsx("span", { className: `${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Max Drawdown" }), _jsx("span", { className: "text-orange-400", children: "-12.3%" })] }) }), _jsx("div", { children: _jsxs("div", { className: "flex justify-between text-sm mb-1", children: [_jsx("span", { className: `${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Sharpe Ratio" }), _jsx("span", { className: "text-green-400", children: "1.45" })] }) })] })] }), _jsxs("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(AlertTriangle, { className: "w-5 h-5 mr-2 text-yellow-400" }), "Risk Alerts"] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: `p-3 rounded-lg ${theme === 'dark' ? 'bg-yellow-900/20' : 'bg-yellow-100/50'}`, children: [_jsx("p", { className: "text-yellow-400 text-sm font-medium", children: "High Correlation" }), _jsx("p", { className: `text-xs ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "BTC and ETH correlation at 0.89" })] }), _jsxs("div", { className: `p-3 rounded-lg ${theme === 'dark' ? 'bg-red-900/20' : 'bg-red-100/50'}`, children: [_jsx("p", { className: "text-red-400 text-sm font-medium", children: "Position Size" }), _jsx("p", { className: `text-xs ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "BTC position exceeds 25% limit" })] })] })] }), _jsxs("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(TrendingDown, { className: "w-5 h-5 mr-2 text-red-400" }), "Stress Testing"] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "2008 Crisis Scenario" }), _jsx("p", { className: "text-red-400 font-semibold", children: "-34.2%" })] }), _jsxs("div", { children: [_jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "COVID-19 Crash" }), _jsx("p", { className: "text-red-400 font-semibold", children: "-28.7%" })] }), _jsxs("div", { children: [_jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Flash Crash" }), _jsx("p", { className: "text-red-400 font-semibold", children: "-15.3%" })] })] })] })] })] }));
};
