import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Settings, Moon, Sun, Shield, Database, Wifi } from 'lucide-react';
import { useTheme } from '../components/Theme/ThemeProvider';
import { useAccessibility } from '../components/Accessibility/AccessibilityProvider';
export const SettingsView = () => {
    const { theme, toggleTheme } = useTheme();
    const { settings, updateSetting } = useAccessibility();
    return (_jsxs("div", { className: "p-6", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h1", { className: `text-3xl font-bold mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Settings & Configuration" }), _jsx("p", { className: `${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Customize your BOLT AI experience" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsxs("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(Settings, { className: "w-5 h-5 mr-2 text-blue-400" }), "Appearance"] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("label", { className: `font-medium ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Theme" }), _jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Switch between light and dark mode" })] }), _jsx("button", { onClick: toggleTheme, className: `p-2 rounded-lg transition-colors ${theme === 'dark'
                                                    ? 'bg-gray-800 hover:bg-gray-700 text-yellow-400'
                                                    : 'bg-gray-200 hover:bg-gray-300 text-gray-700'}`, children: theme === 'dark' ? _jsx(Sun, { className: "w-5 h-5" }) : _jsx(Moon, { className: "w-5 h-5" }) })] }), _jsxs("div", { children: [_jsx("label", { className: `block font-medium mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Font Size" }), _jsxs("select", { value: settings.fontSize, onChange: (e) => updateSetting('fontSize', e.target.value), className: `w-full px-3 py-2 rounded-lg border ${theme === 'dark'
                                                    ? 'bg-gray-800 border-gray-600 text-white'
                                                    : 'bg-white border-gray-300 text-gray-900'}`, children: [_jsx("option", { value: "small", children: "Small" }), _jsx("option", { value: "medium", children: "Medium" }), _jsx("option", { value: "large", children: "Large" }), _jsx("option", { value: "extra-large", children: "Extra Large" })] })] })] })] }), _jsxs("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(Shield, { className: "w-5 h-5 mr-2 text-green-400" }), "Accessibility"] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("label", { className: "flex items-center", children: [_jsx("input", { type: "checkbox", checked: settings.highContrast, onChange: (e) => updateSetting('highContrast', e.target.checked), className: "mr-3 rounded" }), _jsxs("div", { children: [_jsx("span", { className: `font-medium ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "High Contrast" }), _jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Increase contrast for better visibility" })] })] }), _jsxs("label", { className: "flex items-center", children: [_jsx("input", { type: "checkbox", checked: settings.reducedMotion, onChange: (e) => updateSetting('reducedMotion', e.target.checked), className: "mr-3 rounded" }), _jsxs("div", { children: [_jsx("span", { className: `font-medium ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Reduced Motion" }), _jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Minimize animations and transitions" })] })] }), _jsxs("label", { className: "flex items-center", children: [_jsx("input", { type: "checkbox", checked: settings.screenReaderMode, onChange: (e) => updateSetting('screenReaderMode', e.target.checked), className: "mr-3 rounded" }), _jsxs("div", { children: [_jsx("span", { className: `font-medium ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Screen Reader Mode" }), _jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Optimize for screen readers" })] })] })] })] }), _jsxs("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(Wifi, { className: "w-5 h-5 mr-2 text-blue-400" }), "API Configuration"] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: `block font-medium mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Binance API Key" }), _jsx("input", { type: "password", placeholder: "Enter your API key", className: `w-full px-3 py-2 rounded-lg border ${theme === 'dark'
                                                    ? 'bg-gray-800 border-gray-600 text-white placeholder-gray-400'
                                                    : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500'}` })] }), _jsxs("div", { children: [_jsx("label", { className: `block font-medium mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Secret Key" }), _jsx("input", { type: "password", placeholder: "Enter your secret key", className: `w-full px-3 py-2 rounded-lg border ${theme === 'dark'
                                                    ? 'bg-gray-800 border-gray-600 text-white placeholder-gray-400'
                                                    : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500'}` })] }), _jsxs("label", { className: "flex items-center", children: [_jsx("input", { type: "checkbox", className: "mr-3 rounded" }), _jsx("span", { className: `${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Use Testnet" })] })] })] }), _jsxs("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(Database, { className: "w-5 h-5 mr-2 text-purple-400" }), "Database"] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { children: [_jsx("span", { className: `font-medium ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Auto Backup" }), _jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Automatically backup database daily" })] }), _jsx("input", { type: "checkbox", className: "rounded", defaultChecked: true })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { children: [_jsx("span", { className: `font-medium ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "Encryption" }), _jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Encrypt sensitive data" })] }), _jsx("input", { type: "checkbox", className: "rounded", defaultChecked: true })] }), _jsx("button", { className: `w-full px-4 py-2 rounded-lg transition-colors ${theme === 'dark'
                                            ? 'bg-purple-600 hover:bg-purple-700 text-white'
                                            : 'bg-purple-500 hover:bg-purple-600 text-white'}`, children: "Backup Now" })] })] })] })] }));
};
