import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Brain, Activity, TrendingUp } from 'lucide-react';
import { useTheme } from '../components/Theme/ThemeProvider';
export const TrainingView = () => {
    const { theme } = useTheme();
    return (_jsxs("div", { className: "p-6", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h1", { className: `text-3xl font-bold mb-2 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: "AI Training Dashboard" }), _jsx("p", { className: `${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Neural network training with real-time metrics and stability monitoring" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsxs("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(Brain, { className: "w-5 h-5 mr-2 text-purple-400" }), "Training Progress"] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between text-sm mb-1", children: [_jsx("span", { className: `${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Current Epoch" }), _jsx("span", { className: "text-purple-400", children: "245/1000" })] }), _jsx("div", { className: `w-full ${theme === 'dark' ? 'bg-gray-700' : 'bg-gray-300'} rounded-full h-2`, children: _jsx("div", { className: "bg-gradient-to-r from-purple-500 to-blue-600 h-2 rounded-full", style: { width: '24.5%' } }) })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Loss (MSE)" }), _jsx("p", { className: "text-xl font-bold text-blue-400", children: "0.0234" })] }), _jsxs("div", { children: [_jsx("p", { className: `text-sm ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Accuracy" }), _jsx("p", { className: "text-xl font-bold text-green-400", children: "73.2%" })] })] })] })] }), _jsxs("div", { className: `${theme === 'dark'
                            ? 'bg-white/10 border-blue-800/30'
                            : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(Activity, { className: "w-5 h-5 mr-2 text-green-400" }), "Stability Monitor"] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Gradient Norm" }), _jsx("span", { className: "text-green-400", children: "0.85" })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Learning Rate" }), _jsx("span", { className: "text-blue-400", children: "0.001" })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: `text-sm ${theme === 'dark' ? 'text-gray-300' : 'text-gray-600'}`, children: "Reset Count" }), _jsx("span", { className: "text-yellow-400", children: "2" })] })] })] })] }), _jsxs("div", { className: `mt-6 ${theme === 'dark'
                    ? 'bg-white/10 border-blue-800/30'
                    : 'bg-white/80 border-blue-200/50'} backdrop-blur-md rounded-xl p-6 border`, children: [_jsxs("h3", { className: `text-lg font-semibold mb-4 flex items-center ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`, children: [_jsx(TrendingUp, { className: "w-5 h-5 mr-2 text-blue-400" }), "Training Metrics"] }), _jsx("div", { className: "h-64 flex items-center justify-center", children: _jsx("p", { className: `${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`, children: "Training metrics visualization will be implemented in Phase 2" }) })] })] }));
};
